---
- name: Create monitor initial keyring
  sudo: yes
  command: ceph-authtool --create-keyring {{ceph_lib_dir}}/tmp/{{cluster_name}}.mon.keyring --gen-key -n mon. --cap mon 'allow *'
  args:
    creates: "{{ceph_lib_dir}}/tmp/{{cluster_name}}.mon.keyring"

- name: Create client admin keyring
  sudo: yes
  command: ceph-authtool --create-keyring {{ceph_conf_dir}}/{{cluster_name}}.client.admin.keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'
    #creates: "{{ceph_conf_dir}}/{{cluster_name}}.client.admin.keyring"

- name: Upload client admin keyring to ansible server
  fetch:
    src: "{{ceph_conf_dir}}/{{cluster_name}}.client.admin.keyring"
    dest: "{{ansible_key_repository}}/{{cluster_name}}/client.admin.keyring" 

- name: Add admin keyring to monitor keyring
  sudo: yes
  command: ceph-authtool {{ceph_lib_dir}}/tmp/{{cluster_name}}.mon.keyring --import-keyring {{ceph_conf_dir}}/{{cluster_name}}.client.admin.keyring

- name: Upload monitor keyring to ansible server
  sudo: yes
  fetch:
    src: "{{ceph_lib_dir}}/tmp/{{cluster_name}}.mon.keyring"
    dest: "{{ansible_key_repository}}/{{cluster_name}}/mon.keyring"

- name: Generate monitor map
  sudo: yes
  command: monmaptool --create --add {{ansible_hostname}} {{ hostvars[inventory_hostname]['ansible_' + monitor_interface]['ipv4']['address'] }} --fsid {{cluster_fsid.stdout}} {{ceph_lib_dir}}/tmp/monmap

- name: Upload cluster monitor map to ansible server
  sudo: yes
  fetch:
    src: "{{ceph_lib_dir}}/tmp/monmap"
    dest: "{{ansible_key_repository}}/{{cluster_name}}/monmap"

- name: Create data directory for monitor
  sudo: yes
  file:
    path: "{{ceph_lib_dir}}/mon/{{cluster_name}}-{{ansible_hostname}}"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Populate the monitor daemon(s) with the monitor map and keyring
  sudo: yes
  command: ceph-mon --conf {{ceph_conf_dir}}/{{cluster_name}}.conf --mkfs -i {{ansible_hostname}} --monmap {{ceph_lib_dir}}/tmp/monmap --keyring {{ceph_lib_dir}}/tmp/{{cluster_name}}.mon.keyring --mon-data {{ceph_lib_dir}}/mon/{{cluster_name}}-{{ansible_hostname}}

- name: Touch file
  local_action: file path="{{ansible_key_repository}}/{{cluster_name}}/initcomplete" state=touch
