---
- name: Install dependencies
  apt: >
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - python-pycurl
    - ntp
    - hdparm

# STABLE
########

# COMMUNITY VERSION

- name: Install the Ceph repository stable key
  apt_key: >
    data="{{ lookup('file', 'cephstable.asc') }}"
    state=present
  when: env == "community"

- name: Add Ceph stable repository
  apt_repository: >
    repo="deb http://ceph.com/debian-{{ ceph_stable_release }}/ {{ ansible_lsb.codename }} main"
    state=present
  when: env == "community"

# ENTERPRISE VERSION

- name: Install Intank Ceph Enterprise repository key
  apt_key: >
    data="{{ lookup('file', 'cephstableice.asc') }}"
    state=present
  when: env == "ice"

- name: Add Inktank Ceph Enterprise repository
  apt_repository: >
    repo="deb file://{{ ceph_stable_ice_temp_path }} {{ ansible_lsb.codename }} main"
    state=present
  when: env == "ice"


# DEV
# ###

- name: Install the Ceph development repository key
  apt_key: >
    data="{{ lookup('file', 'cephdev.asc') }}"
    state=present
  when: env == "dev"

- name: Add Ceph development repository
  apt_repository: >
    repo="deb http://gitbuilder.ceph.com/ceph-deb-{{ ansible_lsb.codename }}-x86_64-basic/ref/{{ ceph_dev_branch }} {{ ansible_lsb.codename }} main"
    state=present
  when: env == "dev"

########

- name: Install Ceph
  apt: >
    pkg={{ item }}
    state=latest
  with_items:
    - ceph
    - ceph-common    #|
    - ceph-fs-common #|--> yes, they are already all dependencies from 'ceph'
    - ceph-fuse      #|--> however while proceding to rolling upgrades and the 'ceph' package upgrade
    - ceph-mds       #|--> they don't get update so we need to force them
    - libcephfs1     #|
